# Comprehensive Pandas for Data Analytics
### Practical Teaching Notebook

Author: Data Analytics Teaching Resource  
Generated: 2026-03-06

## Learning Objectives

By the end of this notebook students will be able to:

- Understand **Pandas Series and DataFrames**
- Load data from **CSV, Excel, JSON**
- Perform **data inspection and cleaning**
- Conduct **data filtering and transformation**
- Perform **groupby analysis**
- Apply **aggregation functions**
- Merge and join datasets
- Perform **time series analysis**
- Create **feature engineering pipelines**
- Export processed datasets

In [1]:
# Install packages if needed (uncomment if running in fresh environment)
# !pip install pandas numpy openpyxl

import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 2.3.1

## 1. Creating Pandas Series

In [2]:
data = [10, 20, 30, 40, 50]

series = pd.Series(data)
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Series with Custom Index

In [3]:
series = pd.Series([100,200,300], index=["A","B","C"])
series

A    100
B    200
C    300
dtype: int64

## 2. Creating DataFrames

In [4]:
data = {
    "Name":["John","Mary","Peter","Linda"],
    "Age":[28,34,29,42],
    "Salary":[50000,65000,58000,72000]
}

df = pd.DataFrame(data)
df

    Name  Age  Salary
0   John   28   50000
1   Mary   34   65000
2  Peter   29   58000
3  Linda   42   72000

## 3. Loading Data from CSV

In [5]:
# Example loading CSV
# df = pd.read_csv("sales_data.csv")

# For demonstration we generate a dataset
np.random.seed(42)

sales = pd.DataFrame({
    "order_id": range(1,101),
    "region": np.random.choice(["North","South","East","West"],100),
    "sales_rep": np.random.choice(["Alice","Bob","Charles","Diana"],100),
    "product": np.random.choice(["Laptop","Phone","Tablet","Monitor"],100),
    "quantity": np.random.randint(1,10,100),
    "price": np.random.randint(200,2000,100)
})

sales["revenue"] = sales["quantity"] * sales["price"]

sales.head()

   order_id region sales_rep  product  quantity  price  revenue
0         1   East   Charles   Tablet         1   1506     1506
1         2   West       Bob  Monitor         1    226      226
2         3  North       Bob   Tablet         3    425     1275
3         4   East     Diana   Laptop         2   1500     3000
4         5   East       Bob  Monitor         5    997     4985

## 4. Inspecting Data

In [6]:
sales.head()
sales.tail()
sales.sample(5)

    order_id region sales_rep product  quantity  price  revenue
30        31  North     Diana   Phone         9    479     4311
83        84   West   Charles  Tablet         5   1999     9995
74        75  North     Diana  Laptop         2    607     1214
10        11   East     Diana  Tablet         1    652      652
84        85   East     Alice   Phone         4    711     2844

In [7]:
sales.shape
sales.columns
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   order_id   100 non-null    int64
 1   region     100 non-null    object
 2   sales_rep  100 non-null    object
 3   product    100 non-null    object
 4   quantity   100 non-null    int32
 5   price      100 non-null    int32
 6   revenue    100 non-null    int32
dtypes: int32(3), int64(1), object(3)
memory usage: 4.4+ KB

In [8]:
sales.describe()

         order_id    quantity        price       revenue
count  100.000000  100.000000   100.000000    100.000000
mean    50.500000    4.830000  1069.360000   5194.580000
std     29.011492    2.628726   499.561091   3893.187085
min      1.000000    1.000000   216.000000    226.000000
25%     25.750000    3.000000   694.250000   1694.250000
50%     50.500000    4.000000  1065.500000   4687.500000
75%     75.250000    7.000000  1452.000000   7053.000000
max    100.000000    9.000000  1999.000000  17145.000000

## 5. Selecting Columns

In [31]:
sales["revenue"]

0      1506
1       226
2      1275
3      3000
4      4985
      ...
95     1500
96    11328
97     5763
98     4644
99    11304
Name: revenue, Length: 100, dtype: int32

In [10]:
sales[["product","revenue"]].head()

   product  revenue
0   Tablet     1506
1  Monitor      226
2   Tablet     1275
3   Laptop     3000
4  Monitor     4985

## 6. Filtering Rows

In [11]:
# revenue greater than 5000
sales[sales["revenue"] > 5000].head()

    order_id region sales_rep product  quantity  price  revenue
5          6   West       Bob  Laptop         6   1832    10992
8          9   East       Bob   Phone         7   1159     8113
9         10  South   Charles  Laptop         8   1704    13632
11        12   East   Charles  Tablet         6   1219     7314
12        13   East     Diana  Laptop         8   1015     8120

In [12]:
# multiple conditions
sales[(sales["region"]=="North") & (sales["revenue"]>5000)].head()

    order_id region sales_rep  product  quantity  price  revenue
35        36  North     Alice  Monitor         8    806     6448
37        38  North     Alice    Phone         9    899     8091
38        39  North   Charles   Tablet         9   1192    10728
57        58  North       Bob    Phone         8   1886    15088
59        60  North     Diana   Tablet         8   1862    14896

## 7. Sorting Data

In [13]:
sales.sort_values("revenue", ascending=False).head()

    order_id region sales_rep  product  quantity  price  revenue
70        71  South     Diana    Phone         9   1905    17145
57        58  North       Bob    Phone         8   1886    15088
59        60  North     Diana   Tablet         8   1862    14896
52        53   East     Alice  Monitor         9   1546    13914
28        29   West     Diana   Laptop         7   1968    13776

## 8. Creating New Columns (Feature Engineering)

In [14]:
sales["discount"] = np.random.uniform(0.05,0.20,len(sales))

sales["net_revenue"] = sales["revenue"] * (1 - sales["discount"])

sales.head()

,order_id,region,sales_rep,product,quantity,price,revenue,discount,net_revenue
0,1,East,Charles,Tablet,1,1506,1506,0.131843,1307.445167
1,2,West,Bob,Monitor,1,226,226,0.191220,182.784343
2,3,North,Bob,Tablet,3,425,1275,0.107915,1137.407871
3,4,East,Diana,Laptop,2,1500,3000,0.194179,2417.464246
4,5,East,Bob,Monitor,5,997,4985,0.185803,4058.774057

## 9. Handling Missing Data

In [15]:
# introduce missing values
sales.loc[0:5,"sales_rep"] = np.nan

sales.isna().sum()

order_id       0
region         0
sales_rep      6
product        0
quantity       0
price          0
revenue        0
discount       0
net_revenue    0
dtype: int64

In [33]:
# drop missing
sales.dropna().head()

,order_id,region,sales_rep,product,quantity,price,revenue,discount,net_revenue,date,month
0,1,East,Unknown,Tablet,1,1506,1506,0.131843,1307.445167,2024-01-01,1
1,2,West,Unknown,Monitor,1,226,226,0.191220,182.784343,2024-01-02,1
2,3,North,Unknown,Tablet,3,425,1275,0.107915,1137.407871,2024-01-03,1
3,4,East,Unknown,Laptop,2,1500,3000,0.194179,2417.464246,2024-01-04,1
4,5,East,Unknown,Monitor,5,997,4985,0.185803,4058.774057,2024-01-05,1

In [17]:
# fill missing
sales["sales_rep"] = sales["sales_rep"].fillna("Unknown")

sales.head()

,order_id,region,sales_rep,product,quantity,price,revenue,discount,net_revenue
0,1,East,Unknown,Tablet,1,1506,1506,0.131843,1307.445167
1,2,West,Unknown,Monitor,1,226,226,0.191220,182.784343
2,3,North,Unknown,Tablet,3,425,1275,0.107915,1137.407871
3,4,East,Unknown,Laptop,2,1500,3000,0.194179,2417.464246
4,5,East,Unknown,Monitor,5,997,4985,0.185803,4058.774057

## 10. GroupBy Analysis

In [18]:
sales.groupby("region")["revenue"].sum()

region
East     110645
North    122403
South    141815
West     144595
Name: revenue, dtype: int32

In [19]:
sales.groupby("product")["revenue"].mean()

product
Laptop     5242.464286
Monitor    4388.629630
Phone      5474.727273
Tablet     5814.434783
Name: revenue, dtype: float64

In [20]:
sales.groupby(["region","product"])["revenue"].sum()

region  product
East    Laptop     24194
        Monitor    29427
        Phone      24554
        Tablet     32470
North   Laptop     18323
        Monitor    44842
        Phone      28010
        Tablet     31228
South   Laptop     41455
        Monitor    21955
        Phone      55145
        Tablet     23260
West    Laptop     62817
        Monitor    22269
        Phone      12735
        Tablet     46774
Name: revenue, dtype: int32

## 11. Aggregation Functions

In [21]:
sales.groupby("region").agg({
    "revenue":["sum","mean","max"],
    "quantity":"sum"
})

       revenue                     quantity
           sum         mean    max      sum
region
East    110645  4610.208333  13914      121
North   122403  6120.150000  15088      111
South   141815  5454.423077  17145      132
West    144595  4819.833333  13776      119

## 12. Pivot Tables

In [22]:
pd.pivot_table(
    sales,
    values="revenue",
    index="region",
    columns="product",
    aggfunc="sum"
)

product  Laptop  Monitor  Phone  Tablet
region
East      24194    29427  24554   32470
North     18323    44842  28010   31228
South     41455    21955  55145   23260
West      62817    22269  12735   46774

## 13. Merging DataFrames

In [23]:
customers = pd.DataFrame({
    "sales_rep":["Alice","Bob","Charles","Diana"],
    "experience":[5,8,3,10]
})

merged = pd.merge(sales, customers, on="sales_rep", how="left")

merged.head()

,order_id,region,sales_rep,product,quantity,price,revenue,discount,net_revenue,experience
0,1,East,Unknown,Tablet,1,1506,1506,0.131843,1307.445167,NaN
1,2,West,Unknown,Monitor,1,226,226,0.191220,182.784343,NaN
2,3,North,Unknown,Tablet,3,425,1275,0.107915,1137.407871,NaN
3,4,East,Unknown,Laptop,2,1500,3000,0.194179,2417.464246,NaN
4,5,East,Unknown,Monitor,5,997,4985,0.185803,4058.774057,NaN

## 14. Concatenation

In [24]:
df1 = sales.head(5)
df2 = sales.tail(5)

pd.concat([df1, df2])

,order_id,region,sales_rep,product,quantity,price,revenue,discount,net_revenue
0,1,East,Unknown,Tablet,1,1506,1506,0.131843,1307.445167
1,2,West,Unknown,Monitor,1,226,226,0.191220,182.784343
2,3,North,Unknown,Tablet,3,425,1275,0.107915,1137.407871
3,4,East,Unknown,Laptop,2,1500,3000,0.194179,2417.464246
4,5,East,Unknown,Monitor,5,997,4985,0.185803,4058.774057
95,96,South,Bob,Monitor,6,250,1500,0.058445,1412.331763
96,97,South,Bob,Phone,6,1888,11328,0.067823,10559.704597
97,98,West,Diana,Tablet,3,1921,5763,0.067629,5373.254436
98,99,South,Alice,Laptop,6,774,4644,0.147382,3959.560104
99,100,North,Charles,Monitor,8,1413,11304,0.161907,9473.806303

## 15. Working with Datetime

In [25]:
dates = pd.date_range(start="2024-01-01", periods=100)

sales["date"] = dates

sales["month"] = sales["date"].dt.month

sales.head()

,order_id,region,sales_rep,product,quantity,price,revenue,discount,net_revenue,date,month
0,1,East,Unknown,Tablet,1,1506,1506,0.131843,1307.445167,2024-01-01,1
1,2,West,Unknown,Monitor,1,226,226,0.191220,182.784343,2024-01-02,1
2,3,North,Unknown,Tablet,3,425,1275,0.107915,1137.407871,2024-01-03,1
3,4,East,Unknown,Laptop,2,1500,3000,0.194179,2417.464246,2024-01-04,1
4,5,East,Unknown,Monitor,5,997,4985,0.185803,4058.774057,2024-01-05,1

## 16. Time Series Analysis

In [26]:
sales.groupby("month")["revenue"].sum()

month
1    151943
2    161487
3    147760
4     58268
Name: revenue, dtype: int32

## 17. Exporting Data

In [27]:
# sales.to_csv("processed_sales.csv", index=False)
# sales.to_excel("processed_sales.xlsx", index=False)

## Practice Exercises

1. Find total revenue by **sales_rep**
2. Find the **top 5 highest revenue orders**
3. Calculate **average revenue per product**
4. Create a pivot table showing **region vs product revenue**
5. Find the **month with the highest revenue**

## End of Notebook

This notebook covers:

- Pandas fundamentals
- Data cleaning
- Data transformation
- Aggregations
- Pivot tables
- Merging datasets
- Time series analysis

Students can now proceed to **advanced analytics and machine learning workflows**.