# Executive Summary

From the results of the analysis of online shop transactions in 2019, there are important points:

1. The highest sales transactions are in December.
2. The city with the most transactions is the city of San Francisco, namely 24.1%.
3. There are 5 best selling items, namely:
     - AA Batteries (4-pack)
     - AAA Batteries (4-pack)
     - Lightning Charging Cable
     - USB-C Charging Cable
     - Wired Headphones
4. There are 3 types of transactions with items that are often purchased simultaneously:
     - iPhone, Lightning Charging Cable, and Wired Headphones.
     - Google phone, USB-C Charging Cable, and Wired Headphones.
     - Vareebadd phone and Wired Headphones.

In [43]:
# Disable warning

import warnings

warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore', category=FutureWarning)

# Note: warnings is a built-in Python module, it is used to control warning messages in your code.
# Warnings are NOT errors. They are just alerts like "This feature will be removed later" or "This method is outdated"
# This warnings tells you that although this code works now, but it may break in future versions of Python or Libraries.

# Load Data

In [44]:
import os
import pandas as pd

all_files = os.listdir()
all_files

# Note: os is a module in Python which stands for Operating System
# It is a built-in Python module used to interact with your computer's operating system

# os.listdir()                          # List files in folder
# os.mkdir("test")                      # Create a folder
# os.remove("a.txt")                    # Delete a file
# os.path.join("folder", "file.csv")    # Safely joins paths
# os.getcwd()                           # Get current working directory
# os.name                               # OS type (Windows, Linux)
# os.chdir                              # Change folder

['sales-analytics.ipynb',
 'Sales_April_2019.csv',
 'Sales_August_2019.csv',
 'Sales_December_2019.csv',
 'Sales_February_2019.csv',
 'Sales_January_2019.csv',
 'Sales_July_2019.csv',
 'Sales_June_2019.csv',
 'Sales_March_2019.csv',
 'Sales_May_2019.csv',
 'Sales_November_2019.csv',
 'Sales_October_2019.csv',
 'Sales_September_2019.csv']

In [45]:
all_data = [] # This line create an empty list to store all monthly datasets

# Get only CSV files
all_files = [file for file in os.listdir()  # os.listdir() => lists all files in the folder
             if file.endswith('.csv')]      # file.endswith('.csv') => keeps only csv files
                                            # [...] => creates list
# Loop through each file
for file in all_files:                      # for file in all_files: => This loops through each CSV file one by one
    df = pd.read_csv(file)                  # pd.read_csv(file) => Reads each CSV file into a DataFrame
                                            # df => temporary dataset for each month
    all_data.append(df)                     # all_data.append(df) => Adds each monthly DataFrame into the list

# Combines all files
all_data = pd.concat(all_data, ignore_index=True)  # pd.concat() => merges all DataFrames into one
                                                   # ignore_index=True => resets index (0,1,2,.....)

In [46]:
all_data.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

In [47]:
all_data.tail()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

In [48]:
all_data.shape

(186850, 6)

In [49]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186850 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 8.6+ MB

# Data Preprocessing

### Are there any missing values?

In [50]:
# Check for missing values
missing_values = all_data.isnull().sum()

# Display columns with missing values and the count of missing values
missing_values = missing_values[missing_values > 0]

if not missing_values.empty:
    print("Columns with missing values:")
    for column, count in missing_values.items():
        print(f"{column}: {count} missing values")
else:
    print("There are no columns with missing value")

Columns with missing values:
Order ID: 545 missing values
Product: 545 missing values
Quantity Ordered: 545 missing values
Price Each: 545 missing values
Order Date: 545 missing values
Purchase Address: 545 missing values

In [51]:
# remove missing values
all_data = all_data.dropna()

In [52]:
#check again after removing
missing_values = all_data.isnull().sum()

# Display columns with missing values and the count of missing values
missing_values = missing_values[missing_values > 0]

if not missing_values.empty:
    print("Columns with missing values:")
    for column, count in missing_values.items():
        print(f"{column}: {count} missing values")
else:
    print("There are no columns with missing value")

There are no columns with missing value

### Is there any duplicate data?

In [53]:
if all_data.duplicated().any():
    print(f"There are as many as {all_data.duplicated().sum()} duplicate data.")
else:
    print("There are no duplicate data.")

There are as many as 618 duplicate data.

In [54]:
# remove duplicate rows
all_data = all_data.drop_duplicates()

In [55]:
# Check again after removing
if all_data.duplicated().any():
    print(f"There are as many as {all_data.duplicated().sum()} duplicate data.")
else:
    print("There are no duplicate data.")

There are no duplicate data.

In [56]:
all_data.shape

(185687, 6)

# Analyze

### What is the most successful month for sales?

In this question, we use three features, namely: 'Quantity Ordered', 'Price Each', and 'Order Date'.
- Order Quantity and Price Each are used to see how many sales.
- Order Date is used to indicate the month in which sales were highest

We extract these three features so that we can answer our questions. To see which month has the most sales, we use a bar chart.

In [57]:
all_data[['Quantity Ordered', 'Price Each', 'Order Date']].dtypes

Quantity Ordered    object
Price Each          object
Order Date          object
dtype: object

In [58]:
# Extract 'Month' from 'Order date'
all_data['Month'] = all_data['Order Date'].apply(lambda x: x.split('/')[0])
all_data['Month'].head()

0    04
2    04
3    04
4    04
5    04
Name: Month, dtype: object

In [59]:
# Ensure data is in the form of numbers
all_data['Month'].unique()

array(['04', '05', 'Order Date', '08', '09', '12', '01', '02', '03', '07',
       '06', '11', '10'], dtype=object)

In [60]:
# Remove 'order date' data
filter_month = all_data['Month'] == 'Order Date'

all_data = all_data[~filter_month]

In [61]:
# Customize the data type of each feature

all_data['Month'] = all_data['Month'].astype(int)
all_data['Quantity Ordered'] = all_data['Quantity Ordered'].astype(int)
all_data['Price Each'] = all_data['Price Each'].astype(float)

In [62]:
all_data[['Quantity Ordered', 'Price Each', 'Order Date']].dtypes

Quantity Ordered      int64
Price Each          float64
Order Date           object
dtype: object

In [63]:
# Viewing 'Sales' by creating the 'Sales' feature
all_data['Sales'] = all_data['Quantity Ordered'] * all_data['Price Each']
all_data['Sales'].head()

# Explanation on the code
# all_data['Sales'] = means we are creating a new column inside our full dataset called `all_data`
# all_data['Quantity Ordered'] * all_data['Price Each'] means `Sales = Quantity x Price Each`
# all_data['Sales'].head() shows the first five(5) rows of the Sales Column

0     23.90
2     99.99
3    600.00
4     11.99
5     11.99
Name: Sales, dtype: float64

In [ ]:
import plotly.graph_objs as go # We are importing Plotly's graph objects module. This module let's us build interactive charts (not static like Matplotlib)

# Group by month and sum the sales
monthly_sales = all_data.groupby(['Month'])['Sales'].sum()
# groupby(['Month']) => This groups the dataset based on each month (Jan, Feb, e.t.c)
# ['Sales'] => Selects only the Sales Column
# .sum() => Adds up all sales within each month

# Create a line plot trace
trace = go.Scatter(                     # Creating the line chart(Trace)
    x=monthly_sales.index,              # X-axis => Months
    y=monthly_sales.values,             # Y-axis => Total Sales per month 
    mode='lines+markers',               # Draws a line connecting points and markers (dots) on each point
    marker=dict(color='blue'),          # Sets point colour to blue
    name='Monthly Sales'                # Label shown in the chart legend
)

# Create layout - This controls how the chart looks
layout = go.Layout(
    title='Monthly Sales',              # This gives us the Chart title
    xaxis=dict(title='Month'),          # This labels the X-axis
    yaxis=dict(title='Sales'),          # This labels the Y-axis
    hovermode='closest',                # When you hover, it shows the closest data point info
)

# Create figure
fig = go.Figure(data=[trace], layout=layout)  # This combines everything together into one object 
                                              # data=[trace] => Your actual plotted data (the line chart we created earlier)
                                              # layout=layout => Your design settings (title, axis labels, e.t.c
# In conclusion, trace => the content(data), layout => the design(style), Figure => the final complete chart
# Show plot
fig.show()              # This renders (displays) the chart on your screen
                        # Without this line, nothing will show

**Highlight**:

In 2019, the highest sales were in December.

### Which city has the highest number of orders?

To see the distribution of the most sales in each city, we use the "'Purchase Address'" feature which contains user purchase addresses. We extract this feature and just take the city. After that we count how many cities there are. To display it, use a pie chart.

In [65]:
all_data['Purchase Address'].head()

0            917 1st St, Dallas, TX 75001
2       682 Chestnut St, Boston, MA 02215
3    669 Spruce St, Los Angeles, CA 90001
4    669 Spruce St, Los Angeles, CA 90001
5       333 8th St, Los Angeles, CA 90001
Name: Purchase Address, dtype: object

In [ ]:
# Extracting the City
# The code below extracts the city from the address column
# .str.split => Splits each address like "917 1st St", "Dallas", "TX 75001"
# .str.get(1) => Picks the second element (index 1) which is the city
# all_data['City'].head() => Previews the result
all_data['City'] = all_data['Purchase Address'].str.split(',').str.get(1)
all_data['City'].head()

0          Dallas
2          Boston
3     Los Angeles
4     Los Angeles
5     Los Angeles
Name: City, dtype: object

In [ ]:
# Creating the Pie Chart
# all_data['City'].value_counts() => Counts how many orders came from each city
# .index                          => Gives the city names used as Labels
# .values                         => Gives the counts used as slice sizes
# go.Pie (...)                    => Builds the pie chart
# go.Figure(...)                  => Wraps everything into a complete chart object
fig = go.Figure(data=[go.Pie(labels=all_data['City'].value_counts().index, values=all_data['City'].value_counts().values)])

# Update layout for better appearance
fig.update_layout(
    title='Distribution of Cities', # This adds a title to the chart
                                    # "Distribution of Cities" = shows how orders are shared across cities
)

# Show the plot
fig.show()                          # Renders the interactive pie chart

**Highlight**

The largest sales distribution in 2019 was in the city of San Francisco. With a total of 44,662 transactions or 24.1% of the population. Followed by the city of Los Angeles with 29,564 or 15.9% of the population and the city of New York with 24,847 or 13.4% of the population.

### Which product had the highest sales volume, and what factors contributed to its popularity?

To see which items have the highest sales, we use the "Quantity Ordered" feature, we add up the transactions for each item. Then we display it using a bar chart.

To see what factors cause high sales, we use the "Price Each" feature. We look at the average price for the number of transactions for each item. After that we display it using a scatter plot.

We combine these two charts (bar and scatter) and then analyze the relationship between item sales and their average price.To see which items have the highest sales, we use the "Quantity Ordered" feature, we add up the transactions for each item. Then we display it using a bar chart.

In [ ]:
# The goal of the code in this cell is to know which product sold the most, and why?
# So, we are analyzing the `Quantity Ordered => sales volume` and `Price Each => pricing factor`
# .groupby(['Product']) => Groups all rows by each product
# .agg({...}) => This performs multiple aggregations at once
# 'Quantity Ordered':'sum' => Adds up total units sold per product
# 'Price Each':'mean' => Calculates the average price of each product
# .reset_index() => Converts grouped index back into a normal column
order_count = all_data.groupby(['Product']).agg({'Quantity Ordered':'sum', 'Price Each':'mean'}).reset_index()
order_count.head()

                  Product  Quantity Ordered  Price Each
0            20in Monitor              4126      109.99
1  27in 4K Gaming Monitor              6239      389.99
2        27in FHD Monitor              7541      149.99
3  34in Ultrawide Monitor              6192      379.99
4   AA Batteries (4-pack)             27615        3.84

In [ ]:
# Import Subplots => This allows you to create advanced charts and especially useful for multiple axes (like this case)
from plotly.subplots import make_subplots

# Create subplots
fig = make_subplots(specs=[[{"secondary_y": True}]]) # You are creating a figure with secondary Y-axis
                                                     # You are creating a chart with two Y-axes
                                                     # Because you are plotting Quantity Ordered (large numbers) and Price Each (small numbers)
                                                     # Note: If you use one axis, the chart will look distorted
# Add bar plot for Quantity Ordered
# This creates a bar chart which shows how many units each product sold
# secondary_y=False => Uses the left Y-axis
# Left axis => Quantity
fig.add_trace(go.Bar(x=order_count['Product'], y=order_count['Quantity Ordered'], name='Quantity Ordered'), secondary_y=False)

# Add line plot for Price Each
# This creates a line chart which shows price trend across products
# secondary_y=True => Uses the right Y-axis
# Right axis => Price
fig.add_trace(go.Scatter(x=order_count['Product'], y=order_count['Price Each'], mode='lines', name='Price Each'), secondary_y=True)

# Update layout
fig.update_layout(
    title='Quantity Ordered and Price Each for Products',           # Chart title
    xaxis=dict(title='Product'),                                    # X-axis => Product names on horizontal axis
    yaxis=dict(title='Quantity Ordered', rangemode='tozero'),       # Y-axis (Left axis) => Quantity Ordered
    yaxis2=dict(title='Price Each', overlaying='y', side='right'),  # Y-axis(2) (Right axis) => Price Each
                                                                    # overlaying='y' => both charts share same space
                                                                    # side='right' => shows on right side
)

# Show the plot
fig.show()          # Shows your combined chart

**Data**

The sales with the most transactions are AAA Batteries, followed by AA Batteries.

**Insights**

From the two items with the most transactions, we can conclude that people have many electronic devices that are powered by batteries, such as: Remote controls, audio devices, toys, etc.

**Action**

The company stocks various types of batteries, not just AAA and AA types. Because electronic devices that use batteries currently use various types of batteries, such as: C and D, 9V batteries, lithium batteries, and rechargeable batteries.

### What is the trend of the most sold product over time?

In this analysis, we use two features, namely: "Products" and "Months". The product feature is used to see the 5 products with the most transactions, while the months feature is to see trends over time.In this analysis, we use two features, namely: "Products" and "Months". The product feature is used to see the 5 products with the most transactions, while the months feature is to see trends over time.

In [ ]:
all_data['Product'].value_counts().index[:5] # all_data['Product'] => selects the Product Column
                                             # .value_counts() => counts how many times each product appears (i.e how many times each product was sold)
                                             # .index => Returns only the product names, not the numbers.
                                             # [:5] => Takes the top 5 products

Index(['USB-C Charging Cable', 'Lightning Charging Cable',
       'AAA Batteries (4-pack)', 'AA Batteries (4-pack)', 'Wired Headphones'],
      dtype='object', name='Product')

In [ ]:
most_sold_product = all_data['Product'].value_counts().index[:5] # It finds the top 5 most sold products in the dataset
                                                                 # Stores the result inside a variable called most_sold_product
most_sold_product

Index(['USB-C Charging Cable', 'Lightning Charging Cable',
       'AAA Batteries (4-pack)', 'AA Batteries (4-pack)', 'Wired Headphones'],
      dtype='object', name='Product')

In [ ]:
most_sold_products_data = all_data[all_data['Product'].isin(most_sold_product)] # most_sold_product => Contains the top 5 products
                                                                                # .isin(most_sold_product) => Checks each row that "Is this product in the top 5 list?"
                                                                                # all_data[...] => Filters only rows where condition is True
most_sold_products_data.head()     # Shows the first few rows of the filtered dataset

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",4,23.90,Dallas
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,11.99,Los Angeles
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",4,11.99,Los Angeles
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016",4,11.95,San Francisco
8,176564,USB-C Charging Cable,1,11.95,04/12/19 10:58,"790 Ridge St, Atlanta, GA 30301",4,11.95,Atlanta

In [ ]:
# Grouping by Month and Product
most_sold_products_data.groupby(['Month','Product']).size()     # This code gives us the output of "Number of orders per product per month"
                                                                # groupby(['Month','Product']) => Groups the data by Month & Product
                                                                # .size() => Counts number of rows (orders) in each group

Month  Product
1      AA Batteries (4-pack)       1037
       AAA Batteries (4-pack)      1084
       Lightning Charging Cable    1069
       USB-C Charging Cable        1171
       Wired Headphones            1004
2      AA Batteries (4-pack)       1274
       AAA Batteries (4-pack)      1320
       Lightning Charging Cable    1393
       USB-C Charging Cable        1511
       Wired Headphones            1179
3      AA Batteries (4-pack)       1672
       AAA Batteries (4-pack)      1645
       Lightning Charging Cable    1749
       USB-C Charging Cable        1766
       Wired Headphones            1512
4      AA Batteries (4-pack)       2062
       AAA Batteries (4-pack)      1988
       Lightning Charging Cable    2197
       USB-C Charging Cable        2074
       Wired Headphones            1888
5      AA Batteries (4-pack)       1821
       AAA Batteries (4-pack)      1888
       Lightning Charging Cable    1929
       USB-C Charging Cable        1879
       Wired Headphones            1729
6      AA Batteries (4-pack)       1540
       AAA Batteries (4-pack)      1451
       Lightning Charging Cable    1560
       USB-C Charging Cable        1531
       Wired Headphones            1334
7      AA Batteries (4-pack)       1555
       AAA Batteries (4-pack)      1554
       Lightning Charging Cable    1690
       USB-C Charging Cable        1667
       Wired Headphones            1434
8      AA Batteries (4-pack)       1357
       AAA Batteries (4-pack)      1340
       Lightning Charging Cable    1354
       USB-C Charging Cable        1339
       Wired Headphones            1191
9      AA Batteries (4-pack)       1314
       AAA Batteries (4-pack)      1281
       Lightning Charging Cable    1324
       USB-C Charging Cable        1451
       Wired Headphones            1173
10     AA Batteries (4-pack)       2240
       AAA Batteries (4-pack)      2234
       Lightning Charging Cable    2414
       USB-C Charging Cable        2437
       Wired Headphones            2091
11     AA Batteries (4-pack)       1970
       AAA Batteries (4-pack)      1999
       Lightning Charging Cable    2044
       USB-C Charging Cable        2054
       Wired Headphones            1777
12     AA Batteries (4-pack)       2716
       AAA Batteries (4-pack)      2828
       Lightning Charging Cable    2887
       USB-C Charging Cable        2979
       Wired Headphones            2537
dtype: int64

In [ ]:
most_sold_products_data.groupby(['Month','Product']).size().unstack() # The output created is a pivot table showing "How each top product performs across different months"
                                                                      # most_sold_products_data is the filtered dataset containing only the top 5 most sold products which we created earlier
                                                                      # .groupby(['Month','Product']) => This groups the data based on two columns which are Month {Time dimension}, and Product {Product Category}
                                                                      # .size() => This counts the number of rows in each group
                                                                      # .unstack() => It reshapes the result from a vertical format to an horizontal format

Product,AA Batteries (4-pack),AAA Batteries (4-pack),Lightning Charging Cable,USB-C Charging Cable,Wired Headphones
Month,,,,,
1,1037,1084,1069,1171,1004
2,1274,1320,1393,1511,1179
3,1672,1645,1749,1766,1512
4,2062,1988,2197,2074,1888
5,1821,1888,1929,1879,1729
6,1540,1451,1560,1531,1334
7,1555,1554,1690,1667,1434
8,1357,1340,1354,1339,1191
9,1314,1281,1324,1451,1173
10,2240,2234,2414,2437,2091
11,1970,1999,2044,2054,1777
12,2716,2828,2887,2979,2537

In [ ]:
grouped_data = most_sold_products_data.groupby(['Month', 'Product']).size().unstack() # Creating the pivot table

# Create traces for each product
traces = [] # Initialize an empty list. This list will store multiple line charts (one per product)
for column in grouped_data.columns: # This loop means "For each product, create a separate line"
    # Create a Line Chart
    trace = go.Scatter(
        x=grouped_data.index,   # X-azis => Months(1 - 12)
        y=grouped_data[column], # Y-axis => Sales for that product
        mode='lines+markers',   # Draws a line + dots
        name=column             # This labels each each line in the legend so that each product appears separately on th chart
    )
    traces.append(trace)        # Add each line to the list
                                # After the loop finishes, traces contains multiple lines, One line per product

# Create layout
layout = go.Layout(
    title='Most Sold Products Over Time', # Title of Chart
    xaxis=dict(title='Month'),            # Label X-axis => Month
    yaxis=dict(title='Number of Sales'),  # Label Y-axis => Sales
    hovermode='closest',                  # Hover shows closest data point
)

# Create figure
fig = go.Figure(data=traces, layout=layout) # Create the Figure
                                            # Combines All product lines(traces) and Chart Styling(layout)

# Show plot
fig.show() # This renders an interactive Plotly chart
# The chart below shows "How do the top 5 products perform across months?"

**Highlight**

Of the 5 best-selling products, these 5 products are unique, namely trends that are almost the same every month.

### Which products are frequently sold together?

In analyzing which items are frequently purchased together, we use the "Order ID" and "Products" features.

In [ ]:
duplicated_data = all_data[all_data['Order ID'].duplicated(keep=False)] # all_data['Order ID'].duplicated(keep=False) => This checks for duplicate Order IDs
duplicated_data.head()  # This then shows Products bought together in the same order which in other words mean "Customers who bought X also bought Y"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City
3,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,600.00,Los Angeles
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,11.99,Los Angeles
18,176574,Google Phone,1,600.00,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001",4,600.00,Los Angeles
19,176574,USB-C Charging Cable,1,11.95,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001",4,11.95,Los Angeles
32,176586,AAA Batteries (4-pack),2,2.99,04/10/19 17:00,"365 Center St, San Francisco, CA 94016",4,5.98,San Francisco

In [ ]:
duplicated_data.shape

(14128, 9)

In [78]:
grouped_products = duplicated_data.groupby(['Order ID'])['Product'].apply(lambda x: ','.join(x)).reset_index().rename(columns={'Product':'Grouped Products'})
grouped_products.head()

  Order ID                                Grouped Products
0   141275           USB-C Charging Cable,Wired Headphones
1   141290  Apple Airpods Headphones,AA Batteries (4-pack)
2   141365                Vareebadd Phone,Wired Headphones
3   141384               Google Phone,USB-C Charging Cable
4   141450         Google Phone,Bose SoundSport Headphones

In [79]:
grouped_products.shape

(6879, 2)

In [80]:
duplicate_products = duplicated_data.merge(grouped_products, how='left', on='Order ID')
duplicate_products.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Grouped Products
0,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,600.00,Los Angeles,"Google Phone,Wired Headphones"
1,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,11.99,Los Angeles,"Google Phone,Wired Headphones"
2,176574,Google Phone,1,600.00,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001",4,600.00,Los Angeles,"Google Phone,USB-C Charging Cable"
3,176574,USB-C Charging Cable,1,11.95,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001",4,11.95,Los Angeles,"Google Phone,USB-C Charging Cable"
4,176586,AAA Batteries (4-pack),2,2.99,04/10/19 17:00,"365 Center St, San Francisco, CA 94016",4,5.98,San Francisco,"AAA Batteries (4-pack),Google Phone"

In [81]:
duplicate_products.shape

(14128, 10)

In [82]:
drop_duplicate_order_id = duplicate_products.drop_duplicates(subset=['Order ID'])
drop_duplicate_order_id.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Grouped Products
0,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,600.00,Los Angeles,"Google Phone,Wired Headphones"
2,176574,Google Phone,1,600.00,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001",4,600.00,Los Angeles,"Google Phone,USB-C Charging Cable"
4,176586,AAA Batteries (4-pack),2,2.99,04/10/19 17:00,"365 Center St, San Francisco, CA 94016",4,5.98,San Francisco,"AAA Batteries (4-pack),Google Phone"
6,176672,Lightning Charging Cable,1,14.95,04/12/19 11:07,"778 Maple St, New York City, NY 10001",4,14.95,New York City,"Lightning Charging Cable,USB-C Charging Cable"
8,176681,Apple Airpods Headphones,1,150.00,04/20/19 10:39,"331 Cherry St, Seattle, WA 98101",4,150.00,Seattle,"Apple Airpods Headphones,ThinkPad Laptop"

In [83]:
drop_duplicate_order_id.shape

(6879, 10)

In [84]:
# Get the top 5 grouped products
top_products = drop_duplicate_order_id['Grouped Products'].value_counts()[:5]

# Create pie chart trace
trace = go.Pie(
    labels=top_products.index,
    values=top_products.values,
    hole=0.3,
)

# Create layout
layout = go.Layout(
    title='Top 5 Grouped Products Distribution'
)

# Create figure
fig = go.Figure(data=[trace], layout=layout)

# Show plot
fig.show()

**Data**

Items that are often purchased together are:

1. iPhone. Often buyers when buying an iPhone also buy a lightning charging cable and wired headphones.
2. Google phone. Often buyers when buying a Google phone also buy a USB-C charging cable and wired headphones.
3. Vareebadd phone. Often buyers when buying a Vareebadd phone also buy a USB-C charging cable.

**Insight**

Of these 3 devices (iPhone, Google phone, vareebadd phone) buyers always buy charging cables and headphones too. This is because this device does not provide these accessories.

**Action**

Based on the data and insight provided, online stores must provide a variety of smartphone accessories so that buyers can complete their smartphone needs.